package cc.chenzhihao.typress.infras.persistence.impl.sqlite.pos;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table typress_article
 */
public class ArticlePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.article_title
     *
     * @mbg.generated
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.article_original_content
     *
     * @mbg.generated
     */
    private String articleOriginalContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column typress_article.update_time
     *
     * @mbg.generated
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.id
     *
     * @return the value of typress_article.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.id
     *
     * @param id the value for typress_article.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.article_id
     *
     * @return the value of typress_article.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.article_id
     *
     * @param articleId the value for typress_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.article_title
     *
     * @return the value of typress_article.article_title
     *
     * @mbg.generated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.article_title
     *
     * @param articleTitle the value for typress_article.article_title
     *
     * @mbg.generated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.article_original_content
     *
     * @return the value of typress_article.article_original_content
     *
     * @mbg.generated
     */
    public String getArticleOriginalContent() {
        return articleOriginalContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.article_original_content
     *
     * @param articleOriginalContent the value for typress_article.article_original_content
     *
     * @mbg.generated
     */
    public void setArticleOriginalContent(String articleOriginalContent) {
        this.articleOriginalContent = articleOriginalContent == null ? null : articleOriginalContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.article_content
     *
     * @return the value of typress_article.article_content
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.article_content
     *
     * @param articleContent the value for typress_article.article_content
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.create_time
     *
     * @return the value of typress_article.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.create_time
     *
     * @param createTime the value for typress_article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typress_article.update_time
     *
     * @return the value of typress_article.update_time
     *
     * @mbg.generated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typress_article.update_time
     *
     * @param updateTime the value for typress_article.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", articleId=").append(articleId);
        sb.append(", articleTitle=").append(articleTitle);
        sb.append(", articleOriginalContent=").append(articleOriginalContent);
        sb.append(", articleContent=").append(articleContent);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}