package cc.chenzhihao.typress.infras.persistence.impl.sqlite.mappers;

import cc.chenzhihao.typress.infras.persistence.impl.sqlite.example.ArticlePOExample;
import cc.chenzhihao.typress.infras.persistence.impl.sqlite.pos.ArticlePO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    long countByExample(ArticlePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int deleteByExample(ArticlePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int insert(ArticlePO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int insertSelective(ArticlePO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    List<ArticlePO> selectByExample(ArticlePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    ArticlePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ArticlePO row, @Param("example") ArticlePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ArticlePO row, @Param("example") ArticlePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticlePO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticlePO row);
}