package cc.chenzhihao.typress.infras.persistence.impl.sqlite.mappers;

import cc.chenzhihao.typress.infras.persistence.impl.sqlite.example.ConfigPOExample;
import cc.chenzhihao.typress.infras.persistence.impl.sqlite.pos.ConfigPO;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    long countByExample(ConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int deleteByExample(ConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int insert(ConfigPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int insertSelective(ConfigPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    List<ConfigPO> selectByExample(ConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    ConfigPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ConfigPO row, @Param("example") ConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ConfigPO row, @Param("example") ConfigPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfigPO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table typress_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfigPO row);
}