server:
    port: 8080

spring:
    application:
        name: "typress"
    profiles:
        active: "sqlite"
#    datasource:
#        driver-class-name: org.sqlite.JDBC
#        url: jdbc:sqlite:/data/sqlite/database/typress.db
#        username: root
#        password: 123456

logging:
    config: "classpath:logback-spring.xml"
    level:
        root: info
    pattern: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%level][%X{trace_id}][%C:%line]:%m%n"
    home: "/data/logs"

mybatis:
    mapper-locations: "classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/*/*.xml"
#    mapper-base-packages: "cc.chenzhihao.typress.core.infrastructure.persistence.sqlite.mapper"
    
