server:
    port: 8080

spring:
    application:
        name: "typress"
    datasource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:/data/sqlite/database/typress.db

logging:
    config: "classpath:logback-spring.xml"
    level:
        root: info
    pattern: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%level][%X{trace_id}][%C:%line]:%m%n"
    home: "/data/logs"

mybatis:
    mapper-locations: "classpath:/mybatis/mapper/sqlite/*.xml,classpath:/mybatis/mapper/sqlite/*/*.xml"
    mapper-base-packages: "cc.chenzhihao.typress.core.infrastructure.persistence.sqlite.mapper"
    
