server:
    port: 8080

spring:
    application:
        name: "typress"
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:sqlite://127.0.0.1:3306/typress?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456

logging:
    config: "classpath:logback-spring.xml"
    level:
        root: info
    pattern: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%level][%X{trace_id}][%C:%line]:%m%n"
    home: "/data/logs"

mybatis:
    mapper-locations: "classpath:/mybatis/mapper/mysql/*.xml,classpath:/mybatis/mapper/mysql/*/*.xml"
    mapper-base-packages: "cc.chenzhihao.typress.core.infrastructure.persistence.mysql.mapper"
    
typress:
    persistence:
        type: "mysql"